apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: bangbang
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: bangbangdelivery-auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING
          value: "true"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/bangbang_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: "com.mysql.cj.jdbc.Driver"
        - name: SPRING_DATASOURCE_INITIALIZATION-MODE
          value: "always"
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE-PLATFORM
          value: "org.hibernate.dialect.MySQL8Dialect"
        - name: APP_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: jwt-secret
        - name: APP_JWT_EXPIRATION
          value: "86400000"
        - name: APP_JWT_REFRESHEXPIRATION
          value: "604800000"
        - name: APP_SERVICES_USER-SERVICE_URL
          value: "http://user-service:8082"
        livenessProbe:
          httpGet:
            path: /api/v1/auth/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/auth/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bangbang
  labels:
    app: auth-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: auth-service
  type: ClusterIP 