apiVersion: apps/v1
kind: Deployment
metadata:
  name: demand-service
  namespace: bangbang
  labels:
    app: demand-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demand-service
  template:
    metadata:
      labels:
        app: demand-service
    spec:
      containers:
      - name: demand-service
        image: bangbangdelivery-demand-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: demand-service
  namespace: bangbang
  labels:
    app: demand-service
spec:
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: demand-service
  type: ClusterIP 