version: '3.8'

services:
  # Database
  mysql:
    container_name: bangbang_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bangbang
      MYSQL_USER: bangbang
      MYSQL_PASSWORD: bangbang_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bangbang-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    container_name: bangbang_redis
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bangbang-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  gateway:
    container_name: bangbang_gateway
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./infrastructure/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bangbang-network
    depends_on:
      - auth-service
      - user-service
      - order-service
      - demand-service
      - journey-service
      - payment-service
      - messaging-service
      - notification-service
      - search-service

  # Backend Services
  auth-service:
    container_name: bangbang_auth
    build:
      context: ./backend
      dockerfile: auth-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bangbang
      - SPRING_DATASOURCE_USERNAME=bangbang
      - SPRING_DATASOURCE_PASSWORD=bangbang_password
      - SPRING_REDIS_HOST=redis
    networks:
      - bangbang-network
    depends_on:
      - mysql
      - redis

  user-service:
    container_name: bangbang_user
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bangbang
      - SPRING_DATASOURCE_USERNAME=bangbang
      - SPRING_DATASOURCE_PASSWORD=bangbang_password
      - SPRING_REDIS_HOST=redis
    networks:
      - bangbang-network
    depends_on:
      - mysql
      - redis

  order-service:
    container_name: bangbang_order
    build:
      context: ./backend
      dockerfile: order-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bangbang
      - SPRING_DATASOURCE_USERNAME=bangbang
      - SPRING_DATASOURCE_PASSWORD=bangbang_password
      - SPRING_REDIS_HOST=redis
    networks:
      - bangbang-network
    depends_on:
      - mysql
      - redis

  demand-service:
    container_name: bangbang_demand
    build:
      context: ./backend
      dockerfile: demand-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bangbang
      - SPRING_DATASOURCE_USERNAME=bangbang
      - SPRING_DATASOURCE_PASSWORD=bangbang_password
    networks:
      - bangbang-network
    depends_on:
      - mysql

  journey-service:
    container_name: bangbang_journey
    build:
      context: ./backend
      dockerfile: journey-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bangbang
      - SPRING_DATASOURCE_USERNAME=bangbang
      - SPRING_DATASOURCE_PASSWORD=bangbang_password
    networks:
      - bangbang-network
    depends_on:
      - mysql

  payment-service:
    container_name: bangbang_payment
    build:
      context: ./backend
      dockerfile: payment-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8086
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bangbang
      - SPRING_DATASOURCE_USERNAME=bangbang
      - SPRING_DATASOURCE_PASSWORD=bangbang_password
    networks:
      - bangbang-network
    depends_on:
      - mysql

  messaging-service:
    container_name: bangbang_messaging
    build:
      context: ./backend
      dockerfile: messaging-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8087
      - SPRING_REDIS_HOST=redis
    networks:
      - bangbang-network
    depends_on:
      - redis

  notification-service:
    container_name: bangbang_notification
    build:
      context: ./backend
      dockerfile: notification-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8089
      - SPRING_REDIS_HOST=redis
    networks:
      - bangbang-network
    depends_on:
      - redis

  search-service:
    container_name: bangbang_search
    build:
      context: ./backend
      dockerfile: search-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8090
    networks:
      - bangbang-network

  # Frontend
  frontend:
    container_name: bangbang_frontend
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8088
      - SKIP_PREFLIGHT_CHECK=true
      - DISABLE_ESLINT_PLUGIN=true
      - TSC_COMPILE_ON_ERROR=true
      - ESLINT_NO_DEV_ERRORS=true
    volumes:
      - ./frontend/web/patches:/app/patches
    networks:
      - bangbang-network
    depends_on:
      - gateway

networks:
  bangbang-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 