server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}
    refreshExpiration: ${APP_JWT_REFRESHEXPIRATION}
  services:
    user-service:
      url: ${APP_SERVICES_USER-SERVICE_URL:http://user-service:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.bangbang.auth: DEBUG
    org.springframework.security: INFO 