apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bangbang
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yunf66/bangbang-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_API_URL
          value: "http://gateway:80"
        - name: SKIP_PREFLIGHT_CHECK
          value: "true"
        - name: DISABLE_ESLINT_PLUGIN
          value: "true"
        - name: TSC_COMPILE_ON_ERROR
          value: "true"
        - name: ESLINT_NO_DEV_ERRORS
          value: "true"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bangbang
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend
  type: ClusterIP 