global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']  # API Gateway
        labels:
          application: 'gateway'
      
      # Uncomment as services are added
      # - targets: ['host.docker.internal:8081']  # User Service
      #   labels:
      #     application: 'user-service'
      
      # - targets: ['host.docker.internal:8082']  # Demand Service
      #   labels:
      #     application: 'demand-service'
      
      # - targets: ['host.docker.internal:8083']  # Journey Service
      #   labels:
      #     application: 'journey-service'
      
      # - targets: ['host.docker.internal:8084']  # Matching Service
      #   labels:
      #     application: 'matching-service'
      
      # - targets: ['host.docker.internal:8085']  # Order Service
      #   labels:
      #     application: 'order-service'
      
      # - targets: ['host.docker.internal:8086']  # Payment Service
      #   labels:
      #     application: 'payment-service'
      
      # - targets: ['host.docker.internal:8087']  # Messaging Service
      #   labels:
      #     application: 'messaging-service'
      
      # - targets: ['host.docker.internal:8088']  # KYC Service
      #   labels:
      #     application: 'kyc-service'
      
      # - targets: ['host.docker.internal:8089']  # Review Service
      #   labels:
      #     application: 'review-service'
      
      # - targets: ['host.docker.internal:8090']  # Notification Service
      #   labels:
      #     application: 'notification-service'
      
      # - targets: ['host.docker.internal:8761']  # Eureka Server
      #   labels:
      #     application: 'eureka-server'
      
      # - targets: ['host.docker.internal:8888']  # Config Server
      #   labels:
      #     application: 'config-server'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          service: 'mysql'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'

  - job_name: 'elasticsearch'
    metrics_path: '/_prometheus/metrics'
    static_configs:
      - targets: ['elasticsearch:9200']
        labels:
          service: 'elasticsearch'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-resources' 