server:
  port: 8085
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bangbang_journey?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false 