server:
  port: 8085
  servlet:
    context-path: /api/payments

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/bangbang_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

# Payment Service Configuration
stripe:
  api:
    key: ${STRIPE_API_KEY:stripe_test_key_placeholder}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:webhook_secret_placeholder}

wechat:
  pay:
    appId: ${WECHAT_PAY_APP_ID:wx_app_id_placeholder}
    mchId: ${WECHAT_PAY_MCH_ID:mch_id_placeholder}
    key: ${WECHAT_PAY_KEY:key_placeholder}
    notifyUrl: ${WECHAT_PAY_NOTIFY_URL:https://api.bangbang.com/api/payments/wechat/notify}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bangbang.payment: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 