FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining files
COPY . .

# Expose the port
EXPOSE 8081

# Start the server
CMD ["node", "server.js"] 